name: zallpy_teste
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.8.1
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/iconeapp.png"

flutter:  
  uses-material-design: true

  assets:
    - images/iconeapp.png   
    - images/erro.gif
    - images/check.gif
    - images/loading.gif
    - images/zallpylogo.png
    - images/error.gif
    - images/questions.gif
    - images/finish.gif
    - images/finishline.png
    

